### ISSUE TITLE
Need an alternative to the look command

### ISSUE THREAD

**Issue by brettmichael** [x-motemen/ghq#268]
Homebrew just updated and ghq updated to the latest without the look command.

Previously I would type `ghq look repo<tab>` and get an autocompleted list of the repos that matched. As I have a ton this was something I did a million times a day.

I can't immediately see the alternative command that has been put in to replace look and the suggestion on the ticket to remove it is a huge back tick command.

Are you able to look at implementing an alternative command or putting look back?

**Comment by Songmu** [comment]
True, "ghq look" is gone, but "ghq get --look" works almost exactly the same.

How about setting up the completion function with `ghq get --look repo <tab>`?

In addition, with defining the following shell function, you may write a completion function to it.

```shell
ghq-cd () {
    if [ -n "$1" ]; then
        dir="$(ghq list --full-path --exact "$1")"
        if [ -z "$dir" ]; then
            echo "no directroies found for '$1'"
            return 1
        fi
        cd "$dir"
        return
    fi                                                                                                             echo 'usage: ghq-cd $repo'
    return 1
}
```

Further, I recommend that you set up a mechanism for `cd` in cooperation with filtering tools such as fzf and peco.

For example:

```shell
cd "$(ghq list --full-path | peco)"
```

**Comment by amitbha** [comment]
difficult to understand why take 'look' down...

**Comment by yogidevendra** [comment]
@Songmu I agree with @amitbha . look was the most frequent command I used for ghq. If look is broken and you are suggesting some shell magic as a work-around then defeats the whole purpose of using ghq.
