### ISSUE TITLE
Don't go into a subshell, just cd

### ISSUE THREAD

**Issue by RobertAudi** [x-motemen/ghq#29]
It would be cool if `ghq look` just ran `cd ...` instead of going into a subshell. (The subshell feature annoys me actually...). Or at least add a configuration for it?

**Comment by vlaw** [comment]
The shell function is great.
But if you have some projects whose names are like below,
```
$ ghq list --unique vue
vuerify
vue
```

Executing `ghq look vue` will get into the wrong directory.
 
So, I change the function a little, just in case someone encounter the same problem.

```
ghq () {
    if [ "$1" = look -a -n "$2" ]; then
        cd $(command ghq list -e -p $2) 
        return
    fi

    command ghq "$@"
}
```

> add `-e` to do an exact match.
