### ISSUE TITLE
Pass --jobs flag to git to speed up cloning

### ISSUE THREAD

**Issue by smorimoto** [x-motemen/ghq#296]
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---jobsltngt

**Comment by Songmu** [comment]
This is a good suggestion. I didn't know this useful option existed. Thanks for letting me know.

But, I think adding the `--jobs` option is overkill. It's too specific of Git, and no other VCS has a similar option.

Fortunately, there's a `submodule.fetchJobs` setting in gitconfig, so it may be a good idea to let users know that this exists.

What do you think? @smorimoto

**Comment by smorimoto** [comment]
At first, I didn't think about exposing jobs flag to users from ghq side. The idea was to dynamically pass the jobs flag to git depending on the available processors on the machine and the network bandwidth. However, I haven't had any major problems with writing it to gitconfig for quite a while. So I can close this.

**Comment by smorimoto** [comment]
By the way, thanks for sharing this on Twitter. Perhaps a programmer like me working on a project like facebook/hhvm with many submodules can clone more than twice as fast just by using this trick :)

**Comment by Songmu** [comment]
> The idea was to dynamically pass the jobs flag to git depending on the available processors on the machine and the network bandwidth.

I see!
I hope that git itself behaves that way in future.

**Comment by smorimoto** [comment]
Agreed 🙂
