### ISSUE TITLE
ghq list / get does not working on big sur

### ISSUE THREAD

**Issue by tikidunpon** [x-motemen/ghq#308]
When I exec `ghq list`, then returns error. (ghq get also returns same error.)
but `ghq root` returns correct root.

```sh
% ghq list
     error failed to filter repos while walkLocalRepositories(repo): interrupted system call
```

Do you have any help or solution?

environment
- macOS Big Sur 11.0.1（20B50）
- ghq -v ghq version 1.1.5 (rev:f5ac3e5)
- ghq installed by homebrew
- go version go1.15.5 darwin/amd64

**Comment by Songmu** [comment]
Thanks for the report.
I haven't upgraded to Big Sir yet, so it's very helpful.

If possible, could you build the ghq binary by yourself to see if it works? If you have a Go development environment, you can clone the repository and just `make build` to get the ghq executable written out.

**Comment by tikidunpon** [comment]
Thanks for replying.

I have tried following steps, but I got same result..

```sh
% brew uninstall ghq
% git clone https://github.com/x-motemen/ghq
% cd ghq
% make build
% ./ghq list
     error failed to filter repos while walkLocalRepositories(repo): interrupted system call
```

**Comment by Songmu** [comment]
Thanks for the quick response! Could you tell me your Go version?

**Comment by tikidunpon** [comment]
- go version go1.15.5 darwin/amd64

After comment out ghq root in gitconfig, now ghq list is working. 

```
# [ghq]
# 	root = ~/MyCustomRoot
```

**Comment by tikidunpon** [comment]
I found the reason, When I enable real-time protection software `ghq list` sometimes failed (after big sur) .

**Comment by Songmu** [comment]
Thanks for figuring out the cause!
This is troubling.
