### ISSUE TITLE
ghq list / sort options

### ISSUE THREAD

**Issue by valbeat** [x-motemen/ghq#309]
I often want the sort option in `ghq list`.
For example, repository name, update date, etc.

**Comment by koic** [comment]
It may be better to sort by repository name by default (even without sort option) . As a use case, I use `ghq list -p | sort | peco` to sort and filter by `sort` command.

**Comment by Songmu** [comment]
To speed up the process, the repositories are fetched in parallel, so the output order is not stable.
It's not good, so if it doesn't affect the performance, sorting seems to be a good idea.

**Comment by koic** [comment]
@Songmu great, thanks!
