### ISSUE TITLE
ghq list sometimes fails with interrupted system call

### ISSUE THREAD

**Issue by shogo82148** [x-motemen/ghq#311]
### my environment

```
$ go version
go version go1.16 darwin/amd64
```

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shogoichinose/Library/Caches/go-build"
GOENV="/Users/shogoichinose/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/shogoichinose/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/shogoichinose"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/shogoichinose/src/go.googlesource.com/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sm/3m28zgs52mbd8tzc8j1jylw00000gn/T/go-build3849489458=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### the version of ghq

```
$ ghq --version
ghq version 1.1.5 (rev:f5ac3e5)
```

### the problem

I ran `ghq list` to get the list of repositories, but I got the following error message.

```
$ ghq list
     error failed to filter repos while walkLocalRepositories(repo): interrupted system call
```

### related issues

- fix "interrupted system call" error https://github.com/saracen/walker/pull/5
- x/tools/internal/fastwalk: sometimes fails with "readdirent: interrupted system call" https://github.com/golang/go/issues/44478

**Comment by shogo82148** [comment]
oh, I missed the duplicated issue.
It looks as same as https://github.com/x-motemen/ghq/issues/308

**Comment by shogo82148** [comment]
@tikidunpon Are you still facing the same problem?
If yes, can you try my patch?

```diff
diff --git a/go.mod b/go.mod
index c0587db..e20ffa6 100644
--- a/go.mod
+++ b/go.mod
@@ -14,3 +14,5 @@ require (
        golang.org/x/sync v0.0.0-20200625203802-6e8e738ad208
        gopkg.in/yaml.v2 v2.3.0 // indirect
 )
+
+replace github.com/saracen/walker v0.1.1 => github.com/shogo82148/walker v0.1.2-0.20210223235556-09d564d13dea
```

It applies https://github.com/saracen/walker/pull/5

**Comment by tikidunpon** [comment]
Thanks, I tried that, but it doesn't seem to update the dependencies properly.

I've change this file with the replace directive. 
`/gopath/go/pkg/mod/github.com/x-motemen/ghq@v1.1.5/go.mod`

Then remove `bin` and run `go get github.com/x-motemen/ghq`.

**Comment by tikidunpon** [comment]
After running `go get -u github.com/x-motemen/ghq`, it was fixed, thanks.
