### ISSUE TITLE
Request: binary release for arm64(aarch64) Linux

### ISSUE THREAD

**Issue by watiko** [x-motemen/ghq#331]
The 64-bit version of the Raspberry Pi OS has recently been officially [released](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/). Since this makes it easy to prepare an aarch64 Linux environment, it is useful to have pre-built binaries available.

related:
- #318
- https://github.com/kajisha/asdf-ghq/pull/1

**Comment by shogo82148** [comment]
Hi, can anyone create a new release tag?

It looks that `goxz` generates arm64 binaries by default.
https://github.com/Songmu/goxz/commit/46d8e2941bad3987f8aff884f8aad4007251b854

So, we need only the new release tag to have pre-built arm64 binaries.

**Comment by itchyny** [comment]
Resolved in [v1.3.0](https://github.com/x-motemen/ghq/releases/tag/v1.3.0).
