### ISSUE TITLE
`ghq` get is slow when directory already exists

### ISSUE THREAD

**Issue by davinkevin** [x-motemen/ghq#379]
Hello 👋 

First, thank you for your tool, which is really good and I use it a lot… maybe too much considering this issue 😅. 

Sometimes, when I want to jump into a directory, I use `ghq get -l <repo_url>` and it's very slow (~7 seconds). See `hyperfine` results: 

<img width="763" alt="image" src="https://github.com/x-motemen/ghq/assets/1970922/c205c50d-7cba-4e83-b8f4-05f1790c3dee">

I also include `ghq` in scripts when I have to automate tasks… and it's slow (+2sec), especially when the repository is already here. See results just for a `get` on an already existing repository:

<img width="704" alt="image" src="https://github.com/x-motemen/ghq/assets/1970922/132936ee-c114-4cca-ab88-856e60bbe7c1">

Is there something misconfigured on my setup or it's expected?

**Comment by stong1994** [comment]
In your case, ghq traverses all repositories three times, and I'll explain why:

Firstly, before getting or updating a repository, ghq traverses all repositories to determine if a specific repository exists.

Secondly, after getting or updating a repository, ghq attempts to match the repository with the provided URL. However, it matches the repository's subpath, which results in not finding a match.

Lastly, ghq parses the URL provided by the user and uses the parsed information to match the repository, where it succeeds in finding a match.

Overall, the execution time of the ghq get -l command is approximately three times longer than the ghq get command.

**Comment by stong1994** [comment]
I have created a PR [here](https://github.com/x-motemen/ghq/pull/386) to ensure that it scans all repositories only once in your scenario. By the way, how many projects do you have? I have dozens of projects, and it only takes me 40 milliseconds to scan them.

**Comment by davinkevin** [comment]
Thanks. 

I would say I have more, but how can I count that? 
Due to groups in GitLab, I can't just count folders. 
It should be around ~60 maximum, so not something very big.

Is `ghq` affected by other things stored in `$GHQROOT` root? I just discovered I have `pkg/mod` folder from a `golang` env I've setup some times ago. 

<img width="317" alt="image" src="https://github.com/x-motemen/ghq/assets/1970922/7b3ce4b2-381b-435e-9997-3b52d9155107">

And it contains… ~60k folders 😅.

**Comment by stong1994** [comment]
You can use this command to display the projects: 
```
ghq root --all | xargs -I {} fd --type d --max-depth 4 --hidden .git {} | sed 's/\/\.git//'
```
And, I think `pkg` should not under the workspace 🤔

**Comment by davinkevin** [comment]
<img width="908" alt="image" src="https://github.com/x-motemen/ghq/assets/1970922/769a064c-e655-4e0c-b2ff-ed1b1e0ff53a">

I think `--max-depth 4` reduces the list, because I have groups inside group with GitLab, then we filter some. 
But it should be approximatively that…

about `pkg`, I'll give it a try tomorrow by (re)moving it somewhere else and see if it's fater.
