### ISSUE TITLE
VCS detection broken for codeberg

### ISSUE THREAD

**Issue by bvergnaud** [x-motemen/ghq#396]
Hello 👋🏻 

The VCS detection seems broken with Codeberg repositories:

```
❯ ghq get git@codeberg.org:kiss-community/community.git
     clone ssh://git@codeberg.org/kiss-community/community.git -> /home/bvergnaud/git/codeberg.org/kiss-community/community
     error failed to get "git@codeberg.org:kiss-community/community.git": unsupported VCS, url=ssh://git@codeberg.org/kiss-community/community.git: Get "ssh://git@codeberg.org/kiss-community/community.git?go-get=1": unsupported protocol scheme "ssh"

❯ ghq get --vcs git git@codeberg.org:kiss-community/community.git
     clone ssh://git@codeberg.org/kiss-community/community.git -> /home/bvergnaud/git/codeberg.org/kiss-community/community
       git clone --recursive ssh://git@codeberg.org/kiss-community/community.git /home/bvergnaud/git/codeberg.org/kiss-community/community
Cloning into '/home/bvergnaud/git/codeberg.org/kiss-community/community'...
remote: Enumerating objects: 33823, done.
remote: Counting objects: 100% (6621/6621), done.
remote: Compressing objects: 100% (3298/3298), done.
remote: Total 33823 (delta 3215), reused 6018 (delta 2653), pack-reused 27202
Receiving objects: 100% (33823/33823), 5.96 MiB | 30.19 MiB/s, done.
Resolving deltas: 100% (13797/13797), done.
```

This is a random repository for the sake of the demonstration, but I've tested multiple repositories, and they all seem to behave in the same way.

What I find confusing is that I have managed other Codeberg repositories with `ghq` before and didn't have that issue. I'm pretty new to `ghq`, I've only ever used versions 1.6.1 and 1.6.2, and I can reproduce the issue with both versions, so I assume it's not so much a new bug as an external change that reveals it. If I were to venture a guess, I'd say it might have something to do with [the recent update of the underlying software Forgejo](https://mastodon.social/@Codeberg@social.anoxinon.de/112894115510625406), but that's really just a guess.

Cheers.

**Comment by Songmu** [comment]
I made adjustments in #409, but it's also possible that codeberg no longer supports URLs like `git@...`.

Please try it for now.
